version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: timaoEPumba
      MYSQL_PASSWORD: jabbaTheHut2
      MYSQL_ROOT_PASSWORD: jabbaTheHut2
    ports:
      - "3306"
    expose:
      - 3306

  webapp:
    depends_on:
      - db
    image: timao-e-pumba-image
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080"