version: '3.1'

services:
  webapp:
    build: .
    restart: always
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: timaoEPumba
      MYSQL_PASSWORD: jabbaTheHut2
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: timaoEPumba
      MYSQL_PASSWORD: jabbaTheHut2
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: timao_e_pumba
    volumes:
      - /home/cormacx/timao-e-pumba-db:/var/lib/mysql
